# Generated by Django 3.0.4 on 2020-08-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dor',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='city',
        ),
        migrations.AddField(
            model_name='post',
            name='degree',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
